CREATE TABLE sell (
id_s INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
faktura INTEGER(7) NOT NULL DEFAULT 1,
klient INTEGER NOT NULL DEFAULT 1,
article SMALLINT NOT NULL DEFAULT 1,
qty DOUBLE(20,3) NOT NULL DEFAULT 1
) TYPE=InnoDB;
