CREATE TABLE adresy_src (
id_a INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
Symbol VARCHAR(20),
Nazwa TEXT,
Adres VARCHAR(35),
Kod cHAR(6),
Miasto  VARCHAR(35),
NIP VARCHAR(35),
Tel_kier VARCHAR(35),
Tel_1 VARCHAR(35),
Firma CHAR(3)
);